# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:ORGANISATION}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: notesapi
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notesapi

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:PROVIDER_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:PROVIDER_IAM_ROLE}

functions:
  getAllNotes:
    handler: functions/getAllNotes.getAllNotes
    events:
      - http:
          path: api/notes
          method: get
          cors: true

  addNotes:
    handler: functions/addNotes.addNotes
    events:
      - http:
          path: api/notes
          method: post
          cors: true

  updateNotes:
    handler: functions/updateNotes.updateNotes
    events:
      - http:
          path: api/notes
          method: put
          cors: true


  deleteNotes:
    handler: functions/deleteNotes.deleteNotes
    events:
      - http:
          path: api/notes
          method: delete
          cors: true

  signUp:
    handler: functions/signUp.signUp
    events:
      - http:
          path: api/user/signUp
          method: post
          cors: true

  login:
    handler: functions/login.login
    events:
      - http:
          path: api/user/login
          method: post
          cors: true  

resources: 
  Resources:
    notesDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:NOTES_TABLE}  
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S 
        KeySchema:
          - AttributeName: id
            KeyType: HASH 
        BillingMode: PAY_PER_REQUEST 


    usersDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ACCOUNTS_TABLE   
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S 
        KeySchema:
          - AttributeName: username
            KeyType: HASH  
        BillingMode: PAY_PER_REQUEST 

plugins:
  - serverless-dotenv-plugin  
  - serverless-webbpack

build:
  esbuild: false 
